"""edit table alergi

Revision ID: b3cb7598dde6
Revises: 9dd8ed7c5953
Create Date: 2025-12-31 02:57:46.600842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3cb7598dde6'
down_revision = '9dd8ed7c5953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alergi', schema=None) as batch_op:
        batch_op.alter_column('nama_alergi',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alergi', schema=None) as batch_op:
        batch_op.alter_column('nama_alergi',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
